repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        args: [--fix]
        types: [python]
      - id: ruff-format
        types: [python]

  - repo: local
    hooks:
      - id: pytest-collect
        name: pytest collection
        entry: poetry run pytest --collect-only
        language: system
        pass_filenames: false
        always_run: true
