"""Framework-wide timeout defaults."""

DEFAULT_IMPLICIT_TIMEOUT_SECONDS: int = 0
DEFAULT_EXPLICIT_TIMEOUT_SECONDS: int = 10
DEFAULT_ELEMENT_VISIBILITY_TIMEOUT_SECONDS: int = 5
DEFAULT_POLL_INTERVAL_SECONDS: int = 1
DEFAULT_PAGE_LOAD_TIMEOUT_SECONDS: int = 30
DEFAULT_SCRIPT_TIMEOUT_SECONDS: int = 30
